# install.ps1 — kingdee-knowledge-kit 一键安装(Windows / 兜底路径)
#
# 用法: powershell -ExecutionPolicy Bypass -File install.ps1
#   开关: -InstallRoot <dir>  -NoPath  -NoSkills  -NoVerify  -DryRun
#         -Harness workbuddy,zcode,opencode,pi,agents
#
# 主推安装方式(有 Python 环境时优先用它,升级卸载交给 pipx 管):
#   pipx install kingdee-knowledge-kit
#   然后: kd health
# 本脚本是兜底:无 Python 3 检测到 py/python 才用它,或要连技能一起装、
# 离线、双击运行(在资源管理器里右键 install.ps1 → 使用 PowerShell 运行)。
#
# 效果: kd CLI 装到 ~\.kingdee-kit,bin 加入用户 PATH,技能装到 ~\.agents\skills
#       (workbuddy/zcode/opencode/pi 用 junction 挂同一份),最后跑装机自检。
#
# 去服务化(工单 #20/#22):本脚本不再拷 service\、不再拉服务、不再验 /health
#       ——本地 HTTP 服务与十个端点已删除,kd 进程内直连 kd.core。
param(
    [string]$InstallRoot = (Join-Path $env:USERPROFILE ".kingdee-kit"),
    [switch]$NoPath,
    [switch]$NoSkills,
    [switch]$NoVerify,
    [switch]$DryRun,
    [string]$Harness = "all"
)
$ErrorActionPreference = "Stop"
$Repo = $PSScriptRoot
$Bin = Join-Path $InstallRoot "bin"

function Step($msg) { Write-Host "[install] $msg" }

# 1. Python 探测(仅用于兜底启动器;pipx 路径不需要本脚本)
$pyCmd = $null
if (Get-Command py -ErrorAction SilentlyContinue) { $pyCmd = "py" }
elseif (Get-Command python -ErrorAction SilentlyContinue) { $pyCmd = "python" }
else { Write-Host "[install] 需要 Python 3.8+(未检测到 py/python)" -ForegroundColor Red; exit 1 }
Step "python: $pyCmd"

# 2. 库体 + 启动器
Step "安装到 $InstallRoot"
if (-not $DryRun) {
    New-Item -ItemType Directory -Force -Path (Join-Path $InstallRoot "lib"), $Bin | Out-Null
    $libDst = Join-Path $InstallRoot "lib\kd"
    if (Test-Path $libDst) { Remove-Item $libDst -Recurse -Force }
    Copy-Item (Join-Path $Repo "src\kd") (Join-Path $InstallRoot "lib\") -Recurse -Force
    # 包内数据文件:拆解规则/预算/限速档。缺它内核会静默退回内置默认值——装出来的
    # 行为与开发中的不是同一个东西(历史上漏拷过 query_routes.json 与 kd.py)。
    if (-not (Test-Path (Join-Path $libDst "query_routes.json"))) {
        Write-Host "[install] ✗ 缺 lib\kd\query_routes.json" -ForegroundColor Red; exit 1
    }

    $launcher = @'
#!/usr/bin/env python3
"""kd CLI launcher (generated by install.ps1; library body in ../lib/kd)."""
import os
import sys

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(_ROOT, "lib"))

from kd.cli import main  # noqa: E402

if __name__ == "__main__":
    sys.exit(main())
'@
    $launcher | Set-Content -Path (Join-Path $Bin "kd.py") -Encoding UTF8

    # kd.cmd:Windows 不认 Unix shebang,裸名 kd 必须由 .cmd 承载。
    # ⚠️ 本文件必须 ASCII-only:cmd.exe 按 OEM 码页(zh-CN 上是 GBK)读 .cmd,
    # 非 ASCII 注释会吃掉后续命令。
    $cmd = @'
@echo off
rem kd.cmd - kingdee-knowledge CLI wrapper for Windows cmd / PowerShell.
rem
rem Windows does not honour Unix shebangs: it resolves executables by extension
rem (.exe/.cmd/.bat), so the extension-less bin/kd (bash shim) is unreachable
rem from cmd/PowerShell. Conversely MSYS2/Git Bash does not resolve the bare
rem name `kd` to kd.cmd. Both shims must therefore exist.
rem
rem Python discovery: `py` launcher first (picks a 3.x automatically), then
rem `python` on PATH.
rem
rem NOTE: keep this file ASCII-only. cmd.exe reads .cmd in the OEM codepage
rem (GBK on zh-CN Windows); non-ASCII comments corrupt command parsing.
setlocal
set "KDPY="
where py >nul 2>&1
if %ERRORLEVEL% EQU 0 set "KDPY=py"
if defined KDPY goto :run
where python >nul 2>&1
if %ERRORLEVEL% EQU 0 set "KDPY=python"
:run
if not defined KDPY (
    echo kd: no usable Python found ^(3.8+ required^). Install Python or re-run the installer. 1>&2
    exit /b 1
)
%KDPY% "%~dp0kd.py" %*
'@
    # 写 .cmd 必须显式用 ASCII:PowerShell 5.1 的 -Encoding UTF8 会加 BOM,
    # 且若内容含非 ASCII 会被写坏。改用 .NET 的 ASCII 编码,零 BOM。
    [System.IO.File]::WriteAllText((Join-Path $Bin "kd.cmd"), $cmd,
        (New-Object System.Text.ASCIIEncoding))

    # bin/kd:无扩展名 bash shim,给 Git Bash(MSYS2)用——它不会把裸名 kd 解析到 .cmd。
    $sh = @'
#!/usr/bin/env bash
# cd to the script directory then call python via a relative path: this avoids
# MSYS/GitBash rewriting POSIX absolute paths when passing them to native
# Windows python. Linux/macOS/WSL behaviour is unchanged.
DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$DIR" && exec python3 ./kd.py "$@"
'@
    # 无扩展名的 shim 用 UTF8(无 BOM)写:bash 不认 BOM。
    [System.IO.File]::WriteAllText((Join-Path $Bin "kd"), $sh,
        (New-Object System.Text.UTF8Encoding $false))
}

# 3. PATH(bin 加入用户环境变量,幂等)
if (-not $NoPath) {
    $userPath = [Environment]::GetEnvironmentVariable("Path", "User")
    if ($userPath -and $userPath.Split(";") -contains $Bin) {
        Step "PATH 已包含 $Bin(跳过)"
    } else {
        Step "加入用户 PATH: $Bin(新开终端生效)"
        if (-not $DryRun) {
            $newPath = if ($userPath) { "$userPath;$Bin" } else { $Bin }
            [Environment]::SetEnvironmentVariable("Path", $newPath, "User")
        }
    }
}

# 4. 技能:实体只装一份,放在通用兼容目录 ~\.agents\skills\kingdee-knowledge
#    (agentskills.io 标准,Codex/Claude Code/opencode 原生读取);WorkBuddy/ZCode/pi
#    的目录用 NTFS junction 挂到同一份(junction 无需管理员权限,也不跨卷失败)
#    ——升级一处、全家生效;junction 失败回退为真实拷贝。
if (-not $NoSkills) {
    $skillSrc = Join-Path $Repo "skills\kingdee-knowledge\skills\kingdee-knowledge"
    $canon = Join-Path $env:USERPROFILE ".agents\skills\kingdee-knowledge"
    Step "技能实体 → $canon"
    if (-not $DryRun) {
        if ((Test-Path (Join-Path $canon "SKILL.md")) -and
            -not ((Get-Item $canon -ErrorAction SilentlyContinue).LinkType)) {
            Copy-Item (Join-Path $canon "SKILL.md") (Join-Path $canon "SKILL.md.bak") -Force
        }
        if (Test-Path $canon) { Remove-Item $canon -Recurse -Force }
        New-Item -ItemType Directory -Force -Path $canon | Out-Null
        Copy-Item (Join-Path $skillSrc "*") $canon -Recurse -Force

        $harnessMap = [ordered]@{
            "workbuddy" = Join-Path $env:USERPROFILE ".workbuddy\skills\kingdee-knowledge"
            "zcode"     = Join-Path $env:USERPROFILE ".zcode\skills\kingdee-knowledge"
            "opencode"  = Join-Path $env:USERPROFILE ".config\opencode\skills\kingdee-knowledge"
            "pi"        = Join-Path $env:USERPROFILE ".pi\agent\skills\kingdee-knowledge"
        }
        $targets = if ($Harness -eq "all") { $harnessMap.Keys } else {
            $Harness.Split(",") | ForEach-Object { $_.Trim().ToLower() }
        }
        foreach ($h in $targets) {
            if (-not $harnessMap.Contains($h)) {
                Write-Host "[install] 未知 harness: $h(可选 workbuddy/zcode/opencode/pi/agents/all)" -ForegroundColor Yellow
                continue
            }
            $dest = $harnessMap[$h]
            $parent = Split-Path $dest -Parent
            if (Test-Path $dest) { Remove-Item $dest -Recurse -Force }
            New-Item -ItemType Directory -Force -Path $parent | Out-Null
            try {
                New-Item -ItemType Junction -Path $dest -Target $canon | Out-Null
                Step "技能 → $dest(junction → $canon)"
            } catch {
                New-Item -ItemType Directory -Force -Path $dest | Out-Null
                Copy-Item (Join-Path $skillSrc "*") $dest -Recurse -Force
                Step "技能 → $dest(拷贝;junction 创建失败已回退)"
            }
        }
    }
    Write-Host "  (ZCode 也可用插件面板: Settings→Plugins→Discover→添加本仓库 GitHub 地址→Get)"
}

# 5. 装机自检:验「kd 可执行且真能跑通一条命令」。
#    判据是 tests\kd_regression.py 的离线组(工单 #21;旧的 verify_ksearch.py 已随
#    去服务化删除)——它既不联网也不需要服务,10 项全绿才放行。历史上安装器漏拷过
#    query_routes.json 与 kd.py,装出「残废版」却毫无报错,这里就是那道闸。
#    先补验装出来的那个 kd 本身能跑(回归脚本走仓库内核,不覆盖 bin\kd.cmd 装坏)。
if (-not $DryRun -and -not $NoVerify) {
    Step "冒烟验证:$Bin\kd.cmd health"
    if (Test-Path (Join-Path $Bin "kd.cmd")) {
        & (Join-Path $Bin "kd.cmd") health | Out-Null
        if ($LASTEXITCODE -ne 0) {
            Write-Host "[install] ✗ kd 装出来后无法执行,装机失败" -ForegroundColor Red; exit 1
        }
    } else {
        # 没有 .cmd(非 Windows 或 -NoPath 场景)就直接用 python 调启动器
        & $pyCmd (Join-Path $Bin "kd.py") health | Out-Null
        if ($LASTEXITCODE -ne 0) {
            Write-Host "[install] ✗ kd 装出来后无法执行,装机失败" -ForegroundColor Red; exit 1
        }
    }
    Step "装机自检:tests\kd_regression.py(离线组,不联网)"
    & $pyCmd (Join-Path $Repo "tests\kd_regression.py")
    if ($LASTEXITCODE -ne 0) {
        Write-Host "[install] ✗ 回归未全绿,检查上方 FAIL 项" -ForegroundColor Red; exit 1
    }
    Step "✓ kd 可执行且回归通过"
} elseif ($NoVerify) {
    Step "跳过装机自检(-NoVerify)"
}

Write-Host ""
Write-Host "主推安装方式(有 Python 环境时优先用它,升级卸载交给 pipx 管):" -ForegroundColor Green
Write-Host "  pipx install kingdee-knowledge-kit"
Write-Host "  kd health"
Write-Host ""
Write-Host "完成!试一试:" -ForegroundColor Green
Write-Host "  kd health                                # 内核自检(库模式:无服务、无端口)"
Write-Host "  kd ask ""信用额度怎么控制"" --topk 4      # 资料包(带 synthesisBrief 召回信号),交给调用方 agent 合成"
Write-Host "  kd search ""信用额度控制"" --product 93"
Write-Host "  kd read <id> --kind answer               # 读全文,kind 照抄 search 结果的 type"
Write-Host ""
Write-Host "本套件不合成回答(ADR-0008,零模型依赖):拿到 kd ask 资料包后,由 agent 按"
Write-Host "docs/ANSWER-SPEC.md 合成;子代理提示词模板见技能 SKILL.md。"
Write-Host ""
Write-Host "技能实体在 ~\.agents\skills\kingdee-knowledge(通用兼容,Codex/Claude Code/opencode 直接读取)," -ForegroundColor Green
Write-Host "WorkBuddy/ZCode/pi 目录已用 junction 挂到同一份——升级重跑本脚本一次即全家生效。" -ForegroundColor Green
Write-Host "只想装部分 harness: -Harness zcode,pi"
